#Full path to an empty folder where repository should be cloned
pathtofolder = "/home/theo/Desktop/repofolder"

#Write "true" if related check should be run, anything else is considered to be an unwanted check
[tests]
gitignore = "true"
license = "true"
secret = "true"
readme = "true"
test = "true"
workflow = "true"

#A list off extra options that can be enabled, write "true" if option should be enabled
[extraOptions]

