#Full path to an empty folder where repository should be cloned
pathtofolder = "/home/theo/Desktop/repofolder"

#Write "true" if related check should be run
[tests]
gitignore = "true"
license = "true"
secret = "true"
readme = "true"
test = "true"
workflow = "true"
